[env]
PORT = 8000

[tasks.server]
env = { "RUST_ENV" = "development", "PORT" = "${PORT}" }
install_crate = "cargo-watch"
command = "cargo"
args = [
    "watch", 
    "-x", 
    "run --bin server"
]

[tasks.data_retriever]
install_crate = "cargo-watch"
command = "cargo"
args = [
    "watch",
    "-x",
    "run --bin data_retriever"
]

[tasks.styles]
command = "npx"
args = [
    "tailwindcss",
    "-i",
    "./styles/tailwind.css",
    "-o",
    "./assets/styles/main.css",
    "--watch"
]
